---
- name: Enable module
  command: dnf module enable -y cri-o:1.20
  register: result
  changed_when:
    - '"Enabling module streams" in result.stdout'

- name: Install cri-o
  dnf:
    name: cri-o
    state: present

- name: Start and enable CRI-O
  systemd:
    name: crio
    state: started
    enabled: true

- name: setup userns.conf and copy config
  copy: 
    src: "userns.conf"
    dest: "/etc/sysctl.d/userns.conf"
    mode: 0644
    owner: root
    group: root

- name: edit default grub to allow rootless podman
  lineinfile:
    state: present
    dest: /etc/default/grub
    backrefs: yes
    regexp: '^(GRUB_CMDLINE_LINUX=(?!.* {{ cgroup }})\"[^\"]+)(\".*)'
    line: '\1 {{ cgroup }}=1\2'

- name: rebuild grub
  command: "sudo grub2-mkconfig -o /boot/grub2/grub.cfg"
  register: result
  changed_when:
    - "'done'"

- name: Creating subgid and subuid to allow rootless podman
  file:
    path: "{{ item }}"
    state: file
    mode: 0644
    group: root
    owner: root
  with_items: 
    - ["/etc/subgid","/etc/subuid"]

- name: create podman user
  ansible.builtin.user:
    name: podman
    state: present
    shell: /bin/nologin

- name: add subuids + subgids to podman user 100000-165535 
  command: "usermod --add-subuids 100000-165535 --add-subgids 100000-165535 podman"

- name: edit registeries to only have docker images
  lineinfile:
    dest: /etc/containers/registeries
    regexp: 'unqualified-search-registeries*'
    line: unqualified-search-registeries =["docker.io"]
    state: present
