on: push

jobs:
  molecule:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - uses: gofrolist/molecule-action@v2

