on: push

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - uses: robertdebock/molecule-action@2.6.16
        with:
          image: geerlingguy/docker-fedora34-ansible:latest

